mac and windows build

diff --git a/.github/workflows/manifold.yml b/.github/workflows/manifold.yml
--- a/.github/workflows/manifold.yml
+++ b/.github/workflows/manifold.yml
@@ -206,6 +206,7 @@ jobs:
        ls $env:CUDA_PATH\include
    - name: Install Assimp from source
      shell: bash
+
      run: |
        git clone https://github.com/assimp/assimp.git
        cd assimp
@@ -232,8 +233,10 @@ jobs:
      shell: powershell
      run: |
        echo "List DLL dependencies"
+       $currentDir = Get-Location
+       $binPath = Join-Path -Path $currentDir -ChildPath "build/bin"
+       Add-Content $env:GITHUB_PATH $binPath
        dumpbin /DEPENDENTS build/bin/Clipper2.dll
-       dumpbin /DEPENDENTS build/bin/manifold.dll
 
    #- name: Test ${{matrix.parallel_backend}} with CUDA ${{matrix.cuda_support}}
    #  shell: bash
@@ -250,62 +253,62 @@ jobs:
        name: java_artifacts_${{matrix.parallel_backend}}_${{matrix.cuda_support}}
        path: bindings/java/target/*.jar
 
- # build_mac:
- #   timeout-minutes: 30
- #   strategy:
- #     matrix:
- #       parallel_backend: [NONE, TBB]
- #   runs-on: macos-latest
- #   if: github.event.pull_request.draft == false
- #   steps:
- #   - name: Install common dependencies
- #     run: |
- #       brew install pkg-config assimp
- #       pip install trimesh
- #   - name: Install OpenMP
- #     if: matrix.parallel_backend == 'OMP'
- #     run: brew install libomp
- #   - name: Install TBB
- #     if: matrix.parallel_backend == 'TBB'
- #     run: brew install tbb
- #   - name: Install Java and Maven
- #     run: |
- #       brew install openjdk@11
- #       brew install maven
- #       echo "JAVA_HOME=$(/usr/libexec/java_home -v 11)" >> $GITHUB_ENV
- #   - name: Check Java version
- #     run: java -version
- #   - uses: actions/checkout@v3
- #     with:
- #       submodules: recursive
- #   - uses: jwlawson/actions-setup-cmake@v1.12
- #   - name: Build
- #     run: |
- #       mkdir build
- #       cd build
- #       cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DMANIFOLD_DEBUG=ON -DMANIFOLD_EXPORT=ON -DMANIFOLD_PAR=${{matrix.parallel_backend}} .. && make
- #   - name: Check files
- #     run: |
- #       ls build/meshIO/;
- #       if [[ -f build/meshIO/libmeshIO.dylib ]]; then
- #         echo "Files exist."
- #       else
- #         echo "One or more required files do not exist."
- #         exit 1
- #       fi
- #   - name: Build Java package
- #     run: |
- #       cd bindings/java
- #       mvn package
- #   - name: Test
- #     run: |
- #       cd build/test
- #       ./manifold_test
- #   - name: Upload artifact
- #     uses: actions/upload-artifact@v3
- #     with:
- #       name: java-package-mac
- #       path: bindings/java/target/*.jar
+ build_mac:
+   timeout-minutes: 30
+   strategy:
+     matrix:
+       parallel_backend: [NONE, TBB]
+   runs-on: macos-latest
+   if: github.event.pull_request.draft == false
+   steps:
+   - name: Install common dependencies
+     run: |
+       brew install pkg-config assimp
+       pip install trimesh
+   - name: Install OpenMP
+     if: matrix.parallel_backend == 'OMP'
+     run: brew install libomp
+   - name: Install TBB
+     if: matrix.parallel_backend == 'TBB'
+     run: brew install tbb
+   - name: Install Java and Maven
+     run: |
+       brew install openjdk@11
+       brew install maven
+       echo "JAVA_HOME=$(/usr/libexec/java_home -v 11)" >> $GITHUB_ENV
+   - name: Check Java version
+     run: java -version
+   - uses: actions/checkout@v3
+     with:
+       submodules: recursive
+   - uses: jwlawson/actions-setup-cmake@v1.12
+   - name: Build
+     run: |
+       mkdir build
+       cd build
+       cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DMANIFOLD_DEBUG=ON -DMANIFOLD_EXPORT=ON -DMANIFOLD_PAR=${{matrix.parallel_backend}} .. && make
+   - name: Check files
+     run: |
+       ls build/meshIO/;
+       if [[ -f build/meshIO/libmeshIO.dylib ]]; then
+         echo "Files exist."
+       else
+         echo "One or more required files do not exist."
+         exit 1
+       fi
+   - name: Build Java package
+     run: |
+       cd bindings/java
+       mvn package
+   - name: Test
+     run: |
+       cd build/test
+       ./manifold_test
+   - name: Upload artifact
+     uses: actions/upload-artifact@v3
+     with:
+       name: java-package-mac
+       path: bindings/java/target/*.jar
 
 #  build_nix:
 #    timeout-minutes: 30
